[Interface]
PrivateKey = /5PfYpA/DGiW5rdgHcfyzLm8SbYkiyrP5drjkMET3OU=
Address = 10.10.10.2/32
DNS = 8.8.8.8

[Peer]
PublicKey = HvL9lg+BHmgdyz0tSIpx6ZXQT/ePnsEdZPhIirpOrEo=
PresharedKey = tpedSgKfjJ6fOSf7syixQtopv4yk3Uf2fBgdeiyEca0=
Endpoint = 217.144.185.210:443
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
